import type { Metadata } from 'next';

import { patrickHandSC } from '@/styles/fonts';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={patrickHandSC.className}>{children}</body>
    </html>
  );
}
